/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import baseDeDatos.Conexion;
import java.awt.event.KeyEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import modelo.Enfermo;
import modelo.OperacionesDAO;

/**
 *
 * @author dam
 */
public class PanelAsignar extends javax.swing.JPanel {

    Conexion bd;
    OperacionesDAO operaciones;
    DefaultComboBoxModel comboModel;
    
    
    public PanelAsignar(Conexion bd) {
        initComponents();
        this.bd=bd;
        
        operaciones = new OperacionesDAO(bd);
        comboModel=new DefaultComboBoxModel();
        comboEnfermos.setModel(comboModel);//Asignar modelo al combo
        cargarPacientes();
    }
    
    private void cargarPacientes(){
        comboModel.addElement("Selecciona un paciente");
        comboModel.addAll(operaciones.getEnfermos());//carga todos los enfermos
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEnfermos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtMedCode = new javax.swing.JTextField();
        txtDenominacion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        comboEnfermos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("PACIENTE");

        txtMedCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMedCodeKeyPressed(evt);
            }
        });

        txtDenominacion.setEditable(false);

        jLabel2.setText("CODIGO MEDICAMENTO");

        jButton1.setText("ASIGNAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboEnfermos, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtMedCode, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboEnfermos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenominacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(57, 57, 57)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedCodeKeyPressed
        if (evt.getKeyCode()==KeyEvent.VK_ENTER) {
            String codigo=txtMedCode.getText().trim();
            txtDenominacion.setText(operaciones.getMedicamento(codigo));
        }
    }//GEN-LAST:event_txtMedCodeKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigoMedi=txtMedCode.getText().trim();
        String numeroSeguridadSocial;
        int pos= comboEnfermos.getSelectedIndex();
        int resultado=-1;
        if (pos!=0) {
            Enfermo e=(Enfermo) (comboModel.getElementAt(pos));
            numeroSeguridadSocial=e.getNumeroSeguridadSocial();
            resultado=operaciones.asignarMedicacion(codigoMedi,numeroSeguridadSocial);
             switch(resultado){
                    case 1: JOptionPane.showMessageDialog(this, "Asignacion correcta", "info",JOptionPane.INFORMATION_MESSAGE);
                    break;
                    case -2:JOptionPane.showMessageDialog(this, "Ya existe la medicacion", "info",JOptionPane.INFORMATION_MESSAGE);
                    break;
                    case -1:JOptionPane.showMessageDialog(this, "No existe medicamento", "info",JOptionPane.INFORMATION_MESSAGE);
                    break;
                }
        }else{
            JOptionPane.showMessageDialog(this, "asignacion correcta", "info",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void limpiar(){
        txtDenominacion.setText("");
        txtMedCode.setText("");
        comboEnfermos.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEnfermos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDenominacion;
    private javax.swing.JTextField txtMedCode;
    // End of variables declaration//GEN-END:variables
}
