
package vista;

import baseDeDatos.Conexion;
import control.MyJFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dam
 */
public class VtnOperaciones extends MyJFrame {

    PanelAsignar panelAsignar;
    PanelConsulta panelConsulta;
    Conexion bd;
    
    public VtnOperaciones(char tipoUsuario) {
        initComponents();
        centrar();
        int resultado;
        bd=new Conexion();//Crea la conxion
        resultado = bd.establecer("jdbc:mysql://localhost:3306/prog_primera_base");//La establece
        if (bd.registrarDriver() != 0) {//Comprueba que los drivers están
            JOptionPane.showConfirmDialog(this, "Tiene un problema con la bd");
            System.exit(-1);
        }else{
            bd.cerrar();//cierra la base para que no entre ningun entrometido hasta su uso
        }
        
        if(tipoUsuario=='E')//Por algun motivo los 'E' no pueden asignar
            mnuAsignarM.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuAsignarM = new javax.swing.JMenuItem();
        mnuConsultaM = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuDesconectar = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.FlowLayout());

        jMenu1.setText("Operaciones");

        mnuAsignarM.setText("Asignar medicacion");
        mnuAsignarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAsignarMActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAsignarM);

        mnuConsultaM.setText("Consulta medicacion");
        mnuConsultaM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuConsultaMActionPerformed(evt);
            }
        });
        jMenu1.add(mnuConsultaM);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        mnuDesconectar.setText("Desconectar");
        mnuDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDesconectarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuDesconectar);

        mnuSalir.setText("Salir de la aplicación");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSalir);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDesconectarActionPerformed
        new VtnLogin().setVisible(true);
        dispose();
        pack();
    }//GEN-LAST:event_mnuDesconectarActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        bd.cerrar();//Hay que cerrar la conexión al salir
        dispose();
        pack();
        cerrar();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuAsignarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAsignarMActionPerformed
        cerrarPanel();
        /*
          Al enviar la conexión te ahorras conectarte
          varias veces al servidor, pero reduce la seguridad del programa
         */
        panelAsignar=new PanelAsignar(bd);
        getContentPane().add(panelAsignar);
        pack();
    }//GEN-LAST:event_mnuAsignarMActionPerformed

    private void mnuConsultaMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuConsultaMActionPerformed
        cerrarPanel();
        panelConsulta=new PanelConsulta(bd);
        getContentPane().add(panelConsulta);
        pack();
    }//GEN-LAST:event_mnuConsultaMActionPerformed

    private void cerrarPanel(){
        try{
            this.remove(panelAsignar);
        }catch(Exception ex){
            
        }try{
            this.remove(panelConsulta);
        }catch(Exception ex){
            
        }
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAsignarM;
    private javax.swing.JMenuItem mnuConsultaM;
    private javax.swing.JMenuItem mnuDesconectar;
    private javax.swing.JMenuItem mnuSalir;
    // End of variables declaration//GEN-END:variables
}
